# Generated by Django 3.2.5 on 2021-08-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='owner',
            name='plants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_name', to='api.plant'),
        ),
    ]
